AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ReceiptPlacerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReceiptPlacer
      Handler: app.lambda_handler  # Update to match ReceiptPlacer/app.py
      CodeUri: ReceiptPlacer/  # Point to the directory containing app.py
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Role: !GetAtt ReceiptPlacerRole.Arn
      Environment:
        Variables:
          SECRET_NAME: "google_drive_api"
          REGION_NAME: "us-east-1"
          PARENT_FOLDER_ID:

  ReceiptPlacerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ReceiptPlacerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ReceiptPlacerSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:google_drive_api-*"

Outputs:
  ReceiptPlacerLambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ReceiptPlacerLambda.Arn
